engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true

ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
   - "**.rb"
   - ".js"

exclude_paths:
- tests/**/*
- spec/**/*
- vendor/**/*
- ".codeclimate.yml"
- "**/bootstrap.css"
- "**/bootstrap.css.map"
- "**/bootstrap-*.css.map"
- "**/bootstrap.js"
- "**/bootstrap-*.js"
